/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAccessControlManagerInterface extends ethers.utils.Interface {
  functions: {
    "MINTER_ROLE()": FunctionFragment;
    "userMintNonce(address)": FunctionFragment;
    "verifyMint((address,uint256[],uint256[],uint256,address,bytes),address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userMintNonce",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMint",
    values: [
      {
        to: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
        nonce: BigNumberish;
        signer: string;
        signature: BytesLike;
      },
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMintNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyMint", data: BytesLike): Result;

  events: {};
}

export class IAccessControlManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAccessControlManagerInterface;

  functions: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    userMintNonce(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifyMint(
      _data: {
        to: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
        nonce: BigNumberish;
        signer: string;
        signature: BytesLike;
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

  userMintNonce(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

  verifyMint(
    _data: {
      to: string;
      tokenIds: BigNumberish[];
      amounts: BigNumberish[];
      nonce: BigNumberish;
      signer: string;
      signature: BytesLike;
    },
    _caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

    userMintNonce(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    verifyMint(
      _data: {
        to: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
        nonce: BigNumberish;
        signer: string;
        signature: BytesLike;
      },
      _caller: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    userMintNonce(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    verifyMint(
      _data: {
        to: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
        nonce: BigNumberish;
        signer: string;
        signature: BytesLike;
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userMintNonce(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyMint(
      _data: {
        to: string;
        tokenIds: BigNumberish[];
        amounts: BigNumberish[];
        nonce: BigNumberish;
        signer: string;
        signature: BytesLike;
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
