/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAddressResolverInterface extends ethers.utils.Interface {
  functions: {
    "getAddress(bytes4)": FunctionFragment;
    "getAddressWithCheck(bytes4)": FunctionFragment;
    "registerAddress(bytes4[],address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressWithCheck",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAddress",
    values: [BytesLike[], string[]]
  ): string;

  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressWithCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAddress",
    data: BytesLike
  ): Result;

  events: {
    "AddressRegistered(bytes4,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddressRegistered"): EventFragment;
}

export type AddressRegisteredEvent = TypedEvent<
  [string, string] & { id: string; contractAddress: string }
>;

export class IAddressResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAddressResolverInterface;

  functions: {
    getAddress(_id: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getAddressWithCheck(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    registerAddress(
      _ids: BytesLike[],
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAddress(_id: BytesLike, overrides?: CallOverrides): Promise<string>;

  getAddressWithCheck(
    _id: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  registerAddress(
    _ids: BytesLike[],
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAddress(_id: BytesLike, overrides?: CallOverrides): Promise<string>;

    getAddressWithCheck(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    registerAddress(
      _ids: BytesLike[],
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddressRegistered(bytes4,address)"(
      id?: BytesLike | null,
      contractAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { id: string; contractAddress: string }
    >;

    AddressRegistered(
      id?: BytesLike | null,
      contractAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { id: string; contractAddress: string }
    >;
  };

  estimateGas: {
    getAddress(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getAddressWithCheck(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAddress(
      _ids: BytesLike[],
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAddress(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressWithCheck(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAddress(
      _ids: BytesLike[],
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
