/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IExchangeFeesEscrowInterface extends ethers.utils.Interface {
  functions: {
    "claimRewards(address)": FunctionFragment;
    "depositFees(address,uint256)": FunctionFragment;
    "getClaimableRewards(address)": FunctionFragment;
    "hasExchangeFees()": FunctionFragment;
    "initializeTokenRate()": FunctionFragment;
    "rate()": FunctionFragment;
    "setRate(uint24)": FunctionFragment;
    "totalFees(address)": FunctionFragment;
    "updateUserRewards(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFees",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasExchangeFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeTokenRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalFees", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateUserRewards",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasExchangeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeTokenRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateUserRewards",
    data: BytesLike
  ): Result;

  events: {
    "ExchangeFeesPaid(address,uint256)": EventFragment;
    "FeeUpdated(address,uint24)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExchangeFeesPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeUpdated"): EventFragment;
}

export type ExchangeFeesPaidEvent = TypedEvent<
  [string, BigNumber] & { tokenAddr: string; amount: BigNumber }
>;

export type FeeUpdatedEvent = TypedEvent<
  [string, number] & { operator: string; rate: number }
>;

export class IExchangeFeesEscrow extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IExchangeFeesEscrowInterface;

  functions: {
    claimRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositFees(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getClaimableRewards(
      _user: string,
      overrides?: CallOverrides
    ): Promise<
      [([string, BigNumber] & { token: string; amount: BigNumber })[]] & {
        claimableRewards: ([string, BigNumber] & {
          token: string;
          amount: BigNumber;
        })[];
      }
    >;

    hasExchangeFees(overrides?: CallOverrides): Promise<[boolean]>;

    initializeTokenRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rate(overrides?: CallOverrides): Promise<[number]>;

    setRate(
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalFees(_token: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    updateUserRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimRewards(
    _user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositFees(
    _token: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getClaimableRewards(
    _user: string,
    overrides?: CallOverrides
  ): Promise<([string, BigNumber] & { token: string; amount: BigNumber })[]>;

  hasExchangeFees(overrides?: CallOverrides): Promise<boolean>;

  initializeTokenRate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rate(overrides?: CallOverrides): Promise<number>;

  setRate(
    _rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalFees(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  updateUserRewards(
    _user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimRewards(
      _user: string,
      overrides?: CallOverrides
    ): Promise<([string, BigNumber] & { token: string; amount: BigNumber })[]>;

    depositFees(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getClaimableRewards(
      _user: string,
      overrides?: CallOverrides
    ): Promise<([string, BigNumber] & { token: string; amount: BigNumber })[]>;

    hasExchangeFees(overrides?: CallOverrides): Promise<boolean>;

    initializeTokenRate(overrides?: CallOverrides): Promise<void>;

    rate(overrides?: CallOverrides): Promise<number>;

    setRate(_rate: BigNumberish, overrides?: CallOverrides): Promise<void>;

    totalFees(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateUserRewards(_user: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ExchangeFeesPaid(address,uint256)"(
      tokenAddr?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { tokenAddr: string; amount: BigNumber }
    >;

    ExchangeFeesPaid(
      tokenAddr?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { tokenAddr: string; amount: BigNumber }
    >;

    "FeeUpdated(address,uint24)"(
      operator?: string | null,
      rate?: null
    ): TypedEventFilter<[string, number], { operator: string; rate: number }>;

    FeeUpdated(
      operator?: string | null,
      rate?: null
    ): TypedEventFilter<[string, number], { operator: string; rate: number }>;
  };

  estimateGas: {
    claimRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositFees(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getClaimableRewards(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasExchangeFees(overrides?: CallOverrides): Promise<BigNumber>;

    initializeTokenRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rate(overrides?: CallOverrides): Promise<BigNumber>;

    setRate(
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalFees(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateUserRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositFees(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getClaimableRewards(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasExchangeFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initializeTokenRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setRate(
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalFees(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateUserRewards(
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
