/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestHasTokenUriInterface extends ethers.utils.Interface {
  functions: {
    "getLatestUriVersion(uint256,bool)": FunctionFragment;
    "initialize()": FunctionFragment;
    "parent()": FunctionFragment;
    "setHiddenUri(tuple[])": FunctionFragment;
    "setParent(address)": FunctionFragment;
    "setPublicUri(tuple[])": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tokenUri(uint256,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLatestUriVersion",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "parent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setHiddenUri",
    values: [{ tokenId: BigNumberish; uri: string }[]]
  ): string;
  encodeFunctionData(functionFragment: "setParent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setPublicUri",
    values: [{ tokenId: BigNumberish; uri: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenUri",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLatestUriVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHiddenUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPublicUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenUri", data: BytesLike): Result;

  events: {
    "HiddenUriUpdated(address,uint256,uint256)": EventFragment;
    "ParentSet(address)": EventFragment;
    "PublicUriUpdated(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HiddenUriUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ParentSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublicUriUpdated"): EventFragment;
}

export type HiddenUriUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    parent: string;
    id: BigNumber;
    version: BigNumber;
  }
>;

export type ParentSetEvent = TypedEvent<[string] & { parent: string }>;

export type PublicUriUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    parent: string;
    id: BigNumber;
    version: BigNumber;
  }
>;

export class TestHasTokenUri extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestHasTokenUriInterface;

  functions: {
    getLatestUriVersion(
      _id: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    parent(overrides?: CallOverrides): Promise<[string]>;

    setHiddenUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPublicUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tokenUri(
      _tokenId: BigNumberish,
      _version: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getLatestUriVersion(
    _id: BigNumberish,
    _isPublic: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  parent(overrides?: CallOverrides): Promise<string>;

  setHiddenUri(
    _assets: { tokenId: BigNumberish; uri: string }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setParent(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPublicUri(
    _assets: { tokenId: BigNumberish; uri: string }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokenUri(
    _tokenId: BigNumberish,
    _version: BigNumberish,
    _isPublic: boolean,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getLatestUriVersion(
      _id: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(overrides?: CallOverrides): Promise<void>;

    parent(overrides?: CallOverrides): Promise<string>;

    setHiddenUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    setParent(arg0: string, overrides?: CallOverrides): Promise<void>;

    setPublicUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenUri(
      _tokenId: BigNumberish,
      _version: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "HiddenUriUpdated(address,uint256,uint256)"(
      parent?: string | null,
      id?: BigNumberish | null,
      version?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { parent: string; id: BigNumber; version: BigNumber }
    >;

    HiddenUriUpdated(
      parent?: string | null,
      id?: BigNumberish | null,
      version?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { parent: string; id: BigNumber; version: BigNumber }
    >;

    "ParentSet(address)"(
      parent?: null
    ): TypedEventFilter<[string], { parent: string }>;

    ParentSet(parent?: null): TypedEventFilter<[string], { parent: string }>;

    "PublicUriUpdated(address,uint256,uint256)"(
      parent?: string | null,
      id?: BigNumberish | null,
      version?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { parent: string; id: BigNumber; version: BigNumber }
    >;

    PublicUriUpdated(
      parent?: string | null,
      id?: BigNumberish | null,
      version?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { parent: string; id: BigNumber; version: BigNumber }
    >;
  };

  estimateGas: {
    getLatestUriVersion(
      _id: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    parent(overrides?: CallOverrides): Promise<BigNumber>;

    setHiddenUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPublicUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenUri(
      _tokenId: BigNumberish,
      _version: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLatestUriVersion(
      _id: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    parent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setHiddenUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPublicUri(
      _assets: { tokenId: BigNumberish; uri: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenUri(
      _tokenId: BigNumberish,
      _version: BigNumberish,
      _isPublic: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
