/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestHasRoyaltyInterface extends ethers.utils.Interface {
  functions: {
    "getRoyalty(uint256)": FunctionFragment;
    "initialize(address,uint24)": FunctionFragment;
    "parent()": FunctionFragment;
    "setContractRoyalty(address,uint24)": FunctionFragment;
    "setParent(address)": FunctionFragment;
    "setTokenRoyaltiesBatch(tuple[])": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getRoyalty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "parent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setContractRoyalty",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setParent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setTokenRoyaltiesBatch",
    values: [
      {
        tokenId: BigNumberish;
        royaltyReceiver: string;
        royaltyRate: BigNumberish;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRoyalty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setContractRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenRoyaltiesBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "ContractRoyaltyUpdated(address,address,uint24)": EventFragment;
    "ParentSet(address)": EventFragment;
    "TokenRoyaltyUpdated(address,uint256,address,uint24)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractRoyaltyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ParentSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRoyaltyUpdated"): EventFragment;
}

export type ContractRoyaltyUpdatedEvent = TypedEvent<
  [string, string, number] & { parent: string; receiver: string; rate: number }
>;

export type ParentSetEvent = TypedEvent<[string] & { parent: string }>;

export type TokenRoyaltyUpdatedEvent = TypedEvent<
  [string, BigNumber, string, number] & {
    parent: string;
    tokenId: BigNumber;
    receiver: string;
    rate: number;
  }
>;

export class TestHasRoyalty extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestHasRoyaltyInterface;

  functions: {
    getRoyalty(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { receiver: string; rate: number }>;

    initialize(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    parent(overrides?: CallOverrides): Promise<[string]>;

    setContractRoyalty(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenRoyaltiesBatch(
      _assets: {
        tokenId: BigNumberish;
        royaltyReceiver: string;
        royaltyRate: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getRoyalty(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { receiver: string; rate: number }>;

  initialize(
    _receiver: string,
    _rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  parent(overrides?: CallOverrides): Promise<string>;

  setContractRoyalty(
    _receiver: string,
    _rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setParent(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenRoyaltiesBatch(
    _assets: {
      tokenId: BigNumberish;
      royaltyReceiver: string;
      royaltyRate: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getRoyalty(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { receiver: string; rate: number }>;

    initialize(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    parent(overrides?: CallOverrides): Promise<string>;

    setContractRoyalty(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setParent(arg0: string, overrides?: CallOverrides): Promise<void>;

    setTokenRoyaltiesBatch(
      _assets: {
        tokenId: BigNumberish;
        royaltyReceiver: string;
        royaltyRate: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "ContractRoyaltyUpdated(address,address,uint24)"(
      parent?: string | null,
      receiver?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, number],
      { parent: string; receiver: string; rate: number }
    >;

    ContractRoyaltyUpdated(
      parent?: string | null,
      receiver?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, number],
      { parent: string; receiver: string; rate: number }
    >;

    "ParentSet(address)"(
      parent?: null
    ): TypedEventFilter<[string], { parent: string }>;

    ParentSet(parent?: null): TypedEventFilter<[string], { parent: string }>;

    "TokenRoyaltyUpdated(address,uint256,address,uint24)"(
      parent?: string | null,
      tokenId?: BigNumberish | null,
      receiver?: null,
      rate?: null
    ): TypedEventFilter<
      [string, BigNumber, string, number],
      { parent: string; tokenId: BigNumber; receiver: string; rate: number }
    >;

    TokenRoyaltyUpdated(
      parent?: string | null,
      tokenId?: BigNumberish | null,
      receiver?: null,
      rate?: null
    ): TypedEventFilter<
      [string, BigNumber, string, number],
      { parent: string; tokenId: BigNumber; receiver: string; rate: number }
    >;
  };

  estimateGas: {
    getRoyalty(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    parent(overrides?: CallOverrides): Promise<BigNumber>;

    setContractRoyalty(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenRoyaltiesBatch(
      _assets: {
        tokenId: BigNumberish;
        royaltyReceiver: string;
        royaltyRate: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRoyalty(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    parent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setContractRoyalty(
      _receiver: string,
      _rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setParent(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenRoyaltiesBatch(
      _assets: {
        tokenId: BigNumberish;
        royaltyReceiver: string;
        royaltyRate: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
