/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IContentSubsystemBase,
  IContentSubsystemBaseInterface,
} from "../IContentSubsystemBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "parent",
        type: "address",
      },
    ],
    name: "ParentSet",
    type: "event",
  },
  {
    inputs: [],
    name: "parent",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_parent",
        type: "address",
      },
    ],
    name: "setParent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IContentSubsystemBase__factory {
  static readonly abi = _abi;
  static createInterface(): IContentSubsystemBaseInterface {
    return new utils.Interface(_abi) as IContentSubsystemBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContentSubsystemBase {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IContentSubsystemBase;
  }
}
